# SPDX-License-Identifier: GPL-2.0-only

services:
  odlux:
    image: ${SDNC_WEB_IMAGE}
    container_name: odlux
    hostname: odlux
    environment:
      ENABLE_OAUTH: ${SDNC_ENABLE_OAUTH}
      WEBPROTOCOL: HTTP
      WEBPORT: ${SDNC_WEB_PORT}
      SDNRPROTOCOL: http
      SDNRHOST: controller
      SDNRPORT: ${SDNC_REST_PORT}
      SDNRWEBSOCKETPORT: ${SDNR_WEBSOCKET_PORT}
    labels:
      traefik.enable: "true"
      traefik.http.routers.sdnc-web.entrypoints: websecure
      traefik.http.routers.sdnc-web.rule: Host(`odlux.oam.${HTTP_DOMAIN}`)
      traefik.http.routers.sdnc-web.tls: "true"
      traefik.http.services.sdnc-web.loadbalancer.server.port: ${SDNC_WEB_PORT}
    depends_on:
      controller:
        condition: service_healthy
    ports:
      - "8888:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: odlux
    networks:
      - dmz
      - smo
