# SPDX-License-Identifier: GPL-2.0-only

networks:
  smo:
    external: true
  dmz:
    external: true

services:
  minio:
    image: minio/minio
    container_name: minio-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - 9000:9000
      - 9001:9001
    labels:
      traefik.enable: true
      traefik.http.routers.minio.entrypoints: websecure
      traefik.http.routers.minio.rule: Host(`minio.${HTTP_DOMAIN}`)
      traefik.http.routers.minio.tls: false
      traefik.http.services.minio.loadbalancer.server.port: 9001

      traefik.http.routers.minio.middlewares: minio-iframe-headers
      traefik.http.middlewares.minio-iframe-headers.headers.customresponseheaders.X-Frame-Options: ""
      traefik.http.middlewares.minio-iframe-headers.headers.customresponseheaders.Content-Security-Policy: ""
    volumes:
      - /tmp/minio-test/0:/data
    networks:
      smo:


