# SPDX-License-Identifier: GPL-2.0-only

networks:
  smo:
    external: true

services:
  minio:
    image: ${MINIO_IMAGE}
    container_name: minio-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /tmp/minio-test/0:/data
    networks:
      - smo

  nginx-minio:
    image: nginx:latest
    container_name: nginx-minio-proxy
    volumes:
      - ./nginx-minio.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8087:82"
    depends_on:
      - minio-server
    networks:
      - smo
