version: '3.8'

networks:
  smo:
    external: true

services:
  minio:
    image: minio/minio
    container_name: minio-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /tmp/minio-test/0:/data
    networks:
      - smo

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - minio
    networks:
      - smo
